apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-haty
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0009-tenant/tkrw-pr712-0075-0009-app/devfile-sample-haty@sha256:efbc2149442900aed944fa9fe9c8b4432010e1ac9ecbe9ef819d04b45602b80d
        name: my-nodejs
        resources: {}
status: {}
